### ISSUE TITLE
Front-end overhaul issues, vol. 2

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events#36]
Here's another round of things that should be corrected. Many of these relate to CSS rules that were changed for reasons other than making the site responsive and just need to return back to their original values until we're ready to plan out a more comprehensive redesign with the graphic designers.

**Code stuff:**
- [x] In /app/View/Elements/header.ctp:37, the search form is placed inside `<a class="navbar-brand logo">`
- [x] That same file was indented with 2 spaces, but we're moving between legacy code indented with tabs to new standards that indent with 4 spaces. Any other files indented with 2 spaces should be updated, ideally to 4 spaces.

**When using a full-sized window, and in general:**
- [x] I recommend keeping primary links (home, go to date…) and secondary links (log in, register…) visually separated instead of combined. Having the secondary links appear on top and the ‘Home’ link underneath feels counterintuitive.
- [x] In the ‘Advanced’ dropdown for the search bar, the typeface for the options was changed to Harabara, which seems unnecessary and I think is a bit harder to read.
- [x] Changing the tagline font size from 25px to 1.25rem makes it harder to read, and removing the negative margin-bottom from its `i.icon-me-logo` element makes the letters around and inside that icon misaligned
- [x] `text-shadow` was removed from `#sidebar h2`, which makes these headers a bit harder to read
- [x] The font size for `ul.event_accordion .actions a` was originally 0.8em, but has been increased to 20px, which makes these links larger than any of the text around them. This is distracting and breaks up the flow of the event information.
- [x] In the event accordion, location addresses aren't displayed
- [x] The 'Go to Date' popup changed the alignment of the list of dates from left to center. In general, we try to avoid center-aligning lists, because it creates an uneven line for the eye to follow when scanning through the text.
- [x] Instead of using `.btn-sm` for buttons, regular-sized buttons are recommended so users have a full-sized target for clicking.
- [x] The border for `.widget_controls` has been removed. It should be re-added to help visually separate input from output.
- [x] The margin-top for `#widget_demo p` has been removed, but some sort of space between the widget and the text below it should be re-added.
- [x] A background-color and text-color change was added for links with `:hover` or `.active` that should be removed for now.
- [x] The 'advanced' button for the search bar isn't staying in the same line as the search bar (see comment for example and suggestion)

**When using a medium-sized window:**
- [x] Switching from left-align to center-align on lines such as “May 11, 2017   Today” breaks up the vertical line that visitors scan down when skimming over the page and forces an unnecessary zig-zag pattern.
- [x] Moving the logo from the left to the center of the screen is distracting and misaligns the bottom row to the left and right of it.
- [x] Unnecessary vertical bars have been added between the links in the header

**When using a handheld-device-sized window:**
- [x] The link to 'Home' is midway down the list of links instead of at the top

**Comment by ericadeefox** [comment]
Got most of this out of the way this morning, for these ones in particular I'm gonna aggregate them into a new list so I can write down some things about them 

- [ ] I recommend keeping primary links (home, go to date…) and secondary links (log in, register…) visually separated instead of combined. Having the secondary links appear on top and the ‘Home’ link underneath feels counterintuitive.
I'm wondering if I should just do my best to try to revert to the original header style. I didn't do this because I was worried the header would become this time-consuming overdeveloped thing, but it ended up doing that anyway so it's not a big deal.

CONVERSELY, I could just build a totally new navbar, one that's 50px long and top-fixed like basically every other site built with Bootstrap.

- [ ] In the event accordion, location addresses aren't displayed
??
![Location addresses](http://i.imgur.com/8LkKJkw.png)

- [ ] Instead of using .btn-sm for buttons, regular-sized buttons are recommended so users have a full-sized target for clicking.
Am totally cool with doing away with .btn-sm, I just wanted to make sure to build full-sized targets because the .btn-sm buttons are the same size as the ones on the production site.

**Comment by PhantomWatson** [comment]
![image](https://cloud.githubusercontent.com/assets/1965565/26219733/09bfe0c6-3bde-11e7-9f1d-14fd61590818.png)

I'm not seeing location addresses. They're initially hidden by CSS, and it seems like some JS that's supposed to unhide it isn't doing the trick. Not sure what might be the difference between what you're seeing and what was committed.

**Comment by PhantomWatson** [comment]
> Am totally cool with doing away with .btn-sm, I just wanted to make sure to build full-sized targets because the .btn-sm buttons are the same size as the ones on the production site.

Good thinking. But I think that means that the buttons were originally too small. I'm inclined to take Bootstrap's recommendation about what's a good size for form elements and stuff.

**Comment by ericadeefox** [comment]
![image](http://i.imgur.com/Wt73g9k.png)

There's the function in script.js that's supposed to set `.location_details` & `.address` to `display:block;`. It's from the most recent commit. I have no idea what the difference could be.

**Comment by ericadeefox** [comment]
- [ ] the javascript for series editor isn't working and the dropdown menu for editing individual events does not actually drop down

**Comment by ericadeefox** [comment]
- [ ] Need to bootstrapify the series editor form

**Comment by PhantomWatson** [comment]
Added a new item to the list for this:

![image](https://cloud.githubusercontent.com/assets/1965565/26737145/ef913398-4796-11e7-9317-cb959503afa6.png)

If the word 'Advanced' were replaced with an icon, like the `glyphicon-cog` icon, I think that would take care of it. But support for Glyphicons or Font Awesome or some other icon font would have to be added for that.

**Comment by PhantomWatson** [comment]
Added item "Thumbnails and full images are missing from event accordion"

It's not just a visibility issue; they don't appear to be loaded at all. This may help explain why location details aren't being shown, since the code at https://github.com/BallStateCBER/muncie_events/blob/feature-front-end-conversion/app/webroot/js/script.js#L315 appears to only show those elements if there are thumbnails present.

**Comment by ericadeefox** [comment]
Re: the advanced button--

What resolution/browser is this on?

**Comment by PhantomWatson** [comment]
Firefox, 1936×1056px

**Comment by ericadeefox** [comment]
I can't recreate either of these issues for myself locally, so I'm thinking for whatever reason--this happened before, I remember--they're just not getting committed on Github?

**Comment by ericadeefox** [comment]
Although it just occurred to me that it's really stupid to tie in whether or not an address populates based on whether or not an image loads because events can have addresses without images. I will change that right now...

**Comment by ericadeefox** [comment]
I still can't recreate the thumbnail loading issue. For me, the thumbnails are loading properly, as well as the addresses and location details.

**Comment by PhantomWatson** [comment]
Thumbnail issue removed. It was caused on my side by not having downloaded the image files yet.

**Comment by PhantomWatson** [comment]
I've unchecked "The 'advanced' button for the search bar isn't staying in the same line..."

It looks like this is fixed in Chrome, but it's still split into two lines on Firefox. Can you check on your end to confirm?

I poked around to try to find the cause and no obvious solution jumped out at me.

### Widths of elements in Firefox
- `#EventSearchForm`: 278px
- `#EventFilter`: 159px

### Widths of elements in Chrome
- `#EventSearchForm`: 297px
- `#EventFilter`: 170px

**Comment by ericadeefox** [comment]
![image](https://user-images.githubusercontent.com/12422542/30924646-5c2bc92c-a37d-11e7-86ac-8e1020884dc9.png)

If the header still needs work I'm gonna propose we create a second, completely separate app for the header.

**Comment by ericadeefox** [comment]
https://media.giphy.com/media/3o7aCZmmXtuGwJ4vCw/giphy.gif

If the header needs any more work it's just gonna get its own app

**Comment by ericadeefox** [comment]
Is the address thing still a problem? Because I see the addresses on both browser.
